# Generated by Django 5.0.2 on 2024-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('valor', models.FloatField()),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
